-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Oct 29, 2025 at 08:00 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `chairdb`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `productId` bigint(20) UNSIGNED NOT NULL,
  `catId` bigint(20) UNSIGNED DEFAULT NULL,
  `productName` varchar(100) NOT NULL,
  `price` decimal(10,2) DEFAULT NULL,
  `cuttedPrice` decimal(10,2) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `feature` text DEFAULT NULL,
  `thumbnail` varchar(200) DEFAULT NULL,
  `isVisible` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`productId`, `catId`, `productName`, `price`, `cuttedPrice`, `description`, `feature`, `thumbnail`, `isVisible`, `created_at`, `updated_at`) VALUES
(1, 1, 'MAHARAJA CHAIR', 8499.00, 9500.00, 'This is a mesh-back ergonomic office chair designed for comfortable long-hour seating with breathable mesh back and adjustable features.', '1. Comfortable seating – Soft cushioned seat provides long-hour sitting comfort. 2. Breathable mesh back – Allows air circulation, preventing sweat and heat buildup. 3. Adjustable height – Lets you set the chair at a comfortable level for desk work. 4. Mobility – Smooth rolling wheels for easy movement around your workspace. 5. Back support – Curved back design offers lumbar support, helping reduce back strain. 6. Durable base – Chrome or metal base adds strength and stability. 7. Armrests – Support your arms to reduce shoulder tension.', 'frontend/assets/products/MAHARAJA CHAIR.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(2, 1, 'proprietor chair', 4499.00, 6000.00, 'This high-back executive chair is designed for professionals who value comfort and elegance. The thick padding, ergonomic contouring, and premium leather finish make it ideal for office use, meetings, or home workspaces.', '1. Ergonomic Comfort: High backrest supports the spine and neck, reducing fatigue during long sitting hours. 2. Premium Leather Finish: Soft cushioned seat with elegant quilted leather design for both comfort and style. 3. Adjustable Height: Pneumatic gas lift allows easy seat height adjustment. 4. Smooth Mobility: 360° swivel base with durable caster wheels for easy movement. 5. Strong Build: Chrome-finished metal base ensures stability and long life.', 'frontend/assets/products/proprietor chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(3, 1, 'SHET CHAIR', 4999.00, 5500.00, 'This is a premium high-back executive office chair designed for superior comfort and professional appeal.', 'Ergonomic Support: High backrest with lumbar padding ensures proper spine alignment. • Premium Comfort: Soft, cushioned leather upholstery reduces fatigue during long hours. • Adjustable Height: Gas lift mechanism allows smooth seat height adjustment. • Swivel & Mobility: 360° swivel with durable caster wheels for effortless movement. • Stylish Design: Elegant brown leather finish with quilted detailing adds a touch of luxury to any workspace.', 'frontend/assets/products/SHET CHAIR.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(4, 1, 'Owner chair', 4499.00, 5800.00, 'This vibrant red high-back executive chair combines comfort, functionality, and modern style.', 'Ergonomic Design: High backrest supports the spine and neck for comfortable posture. • Premium Comfort: Thick foam cushioning and padded armrests reduce pressure points. • Adjustable Features: Height and tilt adjustments allow a personalized sitting position. • Durable Build: Chrome-finished metal base ensures strength and stability. • Stylish Appearance: Eye-catching red color adds a bold, professional touch to any office or workspace.', 'frontend/assets/products/Owner chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(5, 1, 'Big b chair', 4799.00, 7000.00, 'This stylish executive office chair features a premium dual-tone design in black and tan leatherette, combining elegance with ergonomic comfort.', 'Ergonomic Comfort: High backrest and padded seat support posture and reduce strain. • Premium Finish: Black and tan leatherette adds a professional and modern look. • Adjustable Design: Smooth height and recline control for personalized seating. • Durable Structure: Metal base and smooth-rolling casters ensure strength and easy mobility. • All-Day Support: Thick cushioning and arm padding enhance long-hour sitting comfort', 'frontend/assets/products/Big b chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(6, 1, 'vice president chair', 8499.00, 10000.00, 'This ergonomic mesh office chair is designed for maximum comfort and breathability.', 'Ergonomic Support: Built-in lumbar support and headrest help maintain natural spine alignment. • Breathable Mesh: Promotes airflow to keep you cool during long working hours. • Adjustable Design: Height, tilt, and armrest adjustments for personalized comfort. • Durable Build: Sturdy metal base with smooth caster wheels for stability and mobility. • Modern Look: Sleek, professional design ideal for home or office setups.', 'frontend/assets/products/vice president chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(7, 1, 'Director chair', 8199.00, 10000.00, 'Premium executive office chair designed for leadership positions with superior comfort and professional aesthetics', 'High-back ergonomic design with lumbar support • Premium leather upholstery with quilted detailing • Adjustable height and tilt mechanisms • 360-degree swivel with smooth-rolling casters • Reinforced metal base for stability and durability • Padded armrests for enhanced comfort', 'frontend/assets/products/Director chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(8, 1, 'CEO Chair', 4499.00, 7000.00, 'Executive office chair designed for top-level management with premium features and sophisticated styling', 'Ergonomic high-back design with headrest • Premium leather or leatherette upholstery • Multiple adjustment options (height, tilt, armrests) • 360-degree swivel capability • Durable metal frame with reinforced base • Professional appearance suitable for corporate environments', 'frontend/assets/products/CEO Chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(9, 2, 'STAFF CHAIR', 4499.00, 5500.00, 'This mid-back mesh office chair offers a perfect blend of comfort, breathability, and style.', 'Breathable Mesh Back: Keeps you cool and prevents sweat build-up during long hours. • Comfortable Cushion Seat: Soft padding provides support and reduces sitting fatigue. • Height & Tilt Adjustment: Allows customized seating posture for better ergonomics. • Durable Chrome Base: Strong and stylish base ensures long life and stability. • Smooth Mobility: 360° swivel and caster wheels enable easy movement across any workspace.', 'frontend/assets/products/STAFF CHAIR.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(10, 2, 'Bank Staff Chair', 4999.00, 6500.00, 'This ergonomic office chair combines comfort, functionality, and modern design to enhance your workspace experience.', 'Ergonomic Design: Supports natural spine alignment for improved posture. Breathable Mesh Back: Enhances air circulation to prevent sweating and discomfort. Soft Padded Seat: High-density foam seat ensures comfort for extended sitting. Adjustable Height: Pneumatic gas lift allows easy seat height customization. 360° Swivel Function: Smooth-rolling wheels provide easy mobility and flexibility. Comfortable Armrests: Fixed armrests reduce shoulder and wrist strain. Sturdy Base: Durable 5-star metal/plastic base ensures stability and longevity.', 'frontend/assets/products/Bank Staff Chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(11, 2, 'Customer chair', 3499.00, 4500.00, 'This is a modern and stylish metal frame chair designed for both comfort and durability.', 'Strong Metal Frame: Built with a sturdy chrome-finished metal frame for long-lasting durability. Comfortable Seating: Padded seat and backrest with soft cushioning provide superior comfort during long sitting hours. Elegant Design: Black upholstery with neat stitching patterns enhances aesthetic appeal. Armrest Support: Smooth wooden armrests with ergonomic design offer additional comfort. Versatile Use: Suitable for offices, conference rooms, visitors areas, or home study rooms. Easy Maintenance: Smooth leatherette surface is easy to clean and maintain. Stable Base: Anti-skid leg tips prevent floor scratches and ensure stability.', 'frontend/assets/products/Customer chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(12, 2, 'Designe chair', 3499.00, 5000.00, 'This is a modern and comfortable visitor chair designed for office, reception, or meeting room use.', 'Durable Build: Strong chrome-plated metal frame provides stability and long-lasting performance. Comfortable Seating: Padded seat and backrest with soft leatherette upholstery for superior comfort. Ergonomic Design: Proper back support and armrests ensure comfortable posture during extended use. Elegant Look: Black cushion with chrome finish gives a professional and modern appearance. Low Maintenance: Easy to clean and resistant to stains or wear. Multipurpose Use: Suitable for offices, reception areas, conference rooms, and waiting lounges.', 'frontend/assets/products/Designe chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(13, 2, 'Confrence chair', 4500.00, 5500.00, 'This is a modern black cushioned chair designed for comfort and durability.', 'Comfortable Design: Soft cushioned seat and backrest provide all-day comfort. Premium Leatherette Upholstery: Smooth, easy-to-clean material resistant to wear and stains. Sturdy Chrome Frame: Rust-resistant metal construction ensures long-lasting durability. Multipurpose Use: Perfect for office visitors, study rooms, conference halls, or reception areas. Ergonomic Armrests: Padded arm supports enhance seating comfort. Low Maintenance: Wipe-clean surface keeps the chair looking new for years. Stable and Balanced: Anti-slip leg caps prevent floor scratches and ensure stability.', 'frontend/assets/products/Confrence chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(14, 2, 'Cinfrss chair', 3399.00, 5800.00, 'This sleek and modern office visitor chair combines comfort, durability, and style.', 'Comfortable Cushioning: Soft, high-density foam seat and backrest for superior comfort. Premium Upholstery: Covered in high-quality leatherette material that is easy to clean and resistant to wear. Sturdy Frame: Built with a robust chrome-finished metal structure for enhanced durability and load-bearing capacity. Padded Armrests: Provides extra comfort and support to arms during extended use. Modern Design: Sleek and professional look suitable for offices, waiting areas, or home workspaces. Low Maintenance: Dust- and stain-resistant surface ensures easy upkeep. Weight Capacity: Can typically support up to 100–120 kg.', 'frontend/assets/products/Cinfrss chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(15, 2, 'Recieption chair', 2999.00, 5000.00, 'This is a metal frame banquet chair designed for multipurpose use in offices, conference halls, restaurants, and events.', 'Sturdy Metal Frame: Built with a strong chrome-plated steel frame for long-lasting support. Comfortable Padding: Soft foam cushioning on the seat and back ensures comfort during extended use. Premium Upholstery: Covered with easy-to-clean leatherette fabric for a professional look. Stackable Design: Chairs can be stacked for easy storage and space optimization. Versatile Use: Suitable for offices, conference halls, restaurants, and events. Modern Aesthetic: Sleek chrome finish with comfortable cushioning for formal and casual settings.', 'frontend/assets/products/Recieption chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(16, 3, 'Cafe chair', 2999.00, 4400.00, 'This elegant bar stool combines modern sophistication with comfort and durability.', 'Stylish Design: Modern gold-finished frame enhances any décor with a touch of glamour. Comfortable Seating: Padded round seat with high-quality leatherette provides long-lasting comfort. Durable Frame: Made from sturdy metal for stability and long-term use. Curved Backrest: Offers ergonomic support for a comfortable sitting experience. Footrest Support: Built-in footrest adds extra comfort and convenience. Versatile Use: Perfect for bars, kitchen counters, restaurants, and lounges. Easy Maintenance: Smooth leatherette surface allows for effortless cleaning.', 'frontend/assets/products/Cafe chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(17, 3, 'Bar 2 chairs', 2999.00, 5500.00, 'This modern adjustable bar stool combines comfort, style, and functionality.', 'Ergonomic Design: Curved seat and backrest provide excellent lumbar support for long sitting sessions. Adjustable Height: Equipped with a gas-lift lever to easily adjust seat height for different counter levels. 360° Swivel Function: Allows free rotation for convenience and flexibility. Sturdy Chrome Base: Polished chrome base ensures stability and durability. Footrest Support: Built-in footrest for enhanced comfort. Premium Upholstery: Soft, easy-to-clean leatherette material adds both luxury and practicality. Stylish Look: Perfect for home bars, kitchen islands, and high counters with its modern, minimalistic appeal.', 'frontend/assets/products/Bar 2 chairs.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(18, 3, 'Chill bar chair', 3499.00, 6000.00, 'This stylish adjustable bar stool chair combines modern design with durable construction.', 'Ergonomic Design: Padded seat and backrest provide comfort for long sitting hours. Height Adjustable: Hydraulic lift mechanism allows smooth height adjustment to suit different counters and tables. 360° Swivel Function: Enables easy movement and accessibility. Sturdy Base: Chrome-plated round base ensures stability and prevents tipping. Built-in Footrest: Offers added support and comfort while seated. Premium Finish: Black leatherette upholstery with stitched detailing for a modern, elegant appearance. Easy to Clean: Smooth, wipeable surfaces ideal for daily use.', 'frontend/assets/products/Chill bar chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(19, 3, 'Bar chair', 2999.00, 4500.00, 'This modern bar stool combines comfort and style with its sleek chrome base and cushioned seat.', 'Key Benefits: • Ergonomic Design: Supports the back and promotes good posture during long hours. • Breathable Mesh Back: Provides excellent airflow to keep you cool and sweat-free. • Comfortable Seating: Soft padded seat reduces pressure and enhances comfort. • Adjustable Height: Gas lift mechanism allows easy height adjustment. • Smooth Movement: 360° swivel and durable wheels for effortless mobility in the workspace.', 'frontend/assets/products/Bar chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(20, 3, 'Drinker chair', 3799.00, 5650.00, 'Modern bar stool with contemporary design featuring pneumatic height adjustment mechanism.', 'Pneumatic gas lift mechanism for easy height adjustment • Modern contemporary aesthetic design • Suitable for home bars and commercial settings • Easy to adjust for different counter heights • Durable construction for long-term use', 'frontend/assets/products/Drinker chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(21, 3, 'Round Stool', 1999.00, 3500.00, 'Backless bar stool with comfortable padded seating and chrome metal frame.', 'Space Saving: Backless design allows sliding under counters • Durability: Chrome metal frame resistant to dings • Easy Maintenance: Faux leather/vinyl seats spill-resistant • Versatility: Round shape allows sitting from any angle • Aesthetic Appeal: Bright upholstery with chrome creates retro/modern look • Value: Affordable fixed-height design • Uniform Look: Consistent seating line along counters', 'frontend/assets/products/Round Stool.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(22, 3, 'Bar Stool', 2499.00, 4000.00, 'Contemporary bar stool with artistic stacked design, featuring red cushioned seats.', 'Material: Sturdy metal frame with chrome finish. Seat: Soft, round, red cushioned seat for comfort. Design: Modern industrial look with geometric structure. Functionality: Stackable for easy storage and artistic display. Base: Circular base for stability and support. Usage: Ideal for bars, cafes, or contemporary interiors.', 'frontend/assets/products/Bar Stool.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(23, 4, 'Taj chair', 2499.00, 4000.00, 'This is a stylish and durable metal chair designed for both home and commercial use.', 'Strong and sturdy metal frame for long-lasting durability. Comfortable padded seat with red fabric upholstery. Elegant black powder-coated finish for rust resistance. Lightweight and easy to move. Compact design suitable for dining rooms, cafeterias, and offices. Easy to clean and maintain. Non-slip leg caps to protect floors and ensure stability', 'frontend/assets/products/Taj chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(24, 4, 'Garden chair', 2999.00, 4500.00, 'This is a modern and comfortable visitor chair designed with a sturdy metal frame and cushioned seating.', 'Comfortable Design: Padded seat and backrest for long sitting comfort. Durable Frame: Strong chrome-finished metal frame ensures stability and longevity. Ergonomic Armrests: Soft arm pads for added support and relaxation. Stylish Look: Black leatherette upholstery gives a professional and elegant appearance. Low Maintenance: Easy to clean and resistant to daily wear and tear. Multi-purpose Use: Ideal for office, visitor, or reception seating.', 'frontend/assets/products/Garden chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(25, 4, 'Normal dining chair', 2999.00, 5000.00, 'Standard dining chair designed for everyday use with comfortable cushioning and durable construction.', 'Comfortable Cushioning: Soft padded seat and backrest for enhanced comfort. Durable Frame: Made with a strong metal frame ensuring long-lasting use. Ergonomic Design: Slightly curved backrest supports proper posture. Compact & Lightweight: Easy to move, ideal for multi-purpose spaces. Low Maintenance: Upholstered in easy-to-clean fabric. Versatile Use: Suitable for office, study, training rooms, or reception areas.', 'frontend/assets/products/Normal dining chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(26, 4, 'Citizen chair', 2999.00, 5000.00, 'Dining chair with stainless steel frame and comfortable cushioning.', 'Strong stainless-steel frame for durability and stability. Soft cushioned seat and back for comfort. Easy-to-clean synthetic leather upholstery. Lightweight and easy to move. Space-saving design ideal for compact areas. Rust-resistant metal finish for long-lasting use. Suitable for multipurpose indoor settings', 'frontend/assets/products/Citizen chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(27, 4, 'Flower chair', 2499.00, 4500.00, 'This is a modern armless chair designed with a sleek and minimalist aesthetic.', 'Ergonomic padded seat and backrest for added comfort. Upholstered in premium black leatherette material. Durable chrome-plated metal frame for long-lasting use. Non-slip leg design for stability and floor protection. Lightweight and easy to move or stack. Ideal for office, meeting rooms, reception areas, and dining spaces', 'frontend/assets/products/Flower chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(28, 5, 'Regency study chair', 3999.00, 7000.00, 'This is a student writing chair with an attached writing pad, designed for classrooms and training institutes.', 'Comfortable cushioned seat and backrest with soft padding. Strong and durable metal frame for stability. Foldable or fixed writing pad made of laminated wood or MDF. Powder-coated frame for rust resistance. Compact and space-saving design. Ideal for classrooms, coaching centers, seminars, and offices. Easy to clean and maintain', 'frontend/assets/products/Regency study chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(29, 5, 'Shell writing chair', 3999.00, 6000.00, 'Study chair with attached writing pad designed for educational and training environments.', 'Durable Construction: Made with a strong metal frame for long-lasting use. Comfortable Seat: Ergonomically molded plastic seat and backrest for proper posture support. Attached Writing Pad: Compact and sturdy wooden/plastic writing pad for easy note-taking. Powder-Coated Frame: Rust-resistant finish for enhanced durability. Non-slip Feet: Fitted with plastic leg caps to prevent floor scratches and ensure stability. Lightweight Design: Easy to move and arrange in classrooms or halls.', 'frontend/assets/products/Shell writing chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(30, 5, 'Floding writing pod study chair', 3199.00, 6000.00, 'Foldable study chair with writing pod designed for space-saving storage and comfortable study sessions.', 'Foldable design for easy storage • Integrated writing pod for note-taking • Ergonomic seating for study comfort • Durable construction for long-term use • Space-saving when folded • Suitable for classrooms and study areas', 'frontend/assets/products/Floding writing pod study chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(31, 6, 'Round Stool', 1999.00, 3500.00, 'Space-saving folding stool with backless design and chrome metal frame.', 'Space Saving: Backless design allows sliding under counters • Durability: Chrome metal frame resistant to dings • Easy Maintenance: Faux leather/vinyl seats spill-resistant • Versatility: Round shape allows sitting from any angle • Aesthetic Appeal: Bright upholstery with chrome creates retro/modern look • Value: Affordable fixed-height design • Uniform Look: Consistent seating line along counters', 'frontend/assets/products/Round Stool.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(32, 6, 'Bar Stool', 2499.00, 4000.00, 'Contemporary folding bar stool with modern design featuring comfortable seating.', 'Contemporary single-pedestal design • Contoured ergonomic seat with supportive low backrest • Chrome pedestal with wide circular base • Hydraulic/pneumatic gas lift for height adjustment • 360-degree swivel capability • Semi-circular footrest for added comfort • Stackable for easy storage', 'frontend/assets/products/Bar Stool.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(33, 6, 'Floded Stool', 1999.00, 3400.00, 'Foldable stool with comfortable cushioned seat and durable metal frame.', 'Compact & Foldable Design: Easy to fold and carry, saves space when stored. Durable Metal Frame: Sturdy construction ensures long-lasting use. Comfortable Cushioned Seat: Soft, padded seat provides enhanced comfort. Non-Slip Rubber Tips: Prevents floor scratches and offers stable support. Lightweight & Portable: Easy to move and perfect for multipurpose use. Versatile Usage: Suitable for kitchen, study, outdoor events, or as extra seating.', 'frontend/assets/products/Floded Stool.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(34, 6, 'Desire Stool', 1999.00, 4500.00, 'This is a foldable stool designed for convenience, portability, and comfort.', 'Foldable Design: Easy to fold and store when not in use, saving space. Comfortable Cushion: Soft, padded seat with a smooth surface for enhanced comfort. Durable Frame: Made from strong metal for stability and long-lasting use. Anti-Slip Feet: Rubber tips on legs prevent slipping and protect floors from scratches. Lightweight & Portable: Easy to carry and move around, perfect for indoor and outdoor use. Multipurpose Use: Suitable for kitchen, study, makeup, office, or extra seating anywhere.', 'frontend/assets/products/Desire Stool.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(35, 7, 'Hospital 3 seaters chair', 9999.00, 13000.00, 'This three-seater stainless steel waiting chair is designed for durability, comfort, and modern appeal.', 'Material: High-quality stainless steel with anti-rust coating for long-lasting durability. Design: Ergonomic three-seater design with comfortable back support. Finish: Smooth, polished surface that resists stains and scratches. Armrests: Sturdy side armrests for added comfort and support. Legs: Strong metallic frame with anti-skid foot pads for stability. Maintenance: Easy to clean and maintain; ideal for heavy use in public areas. Usage: Suitable for hospitals, offices, airports, banks, and other waiting lounges.', 'frontend/assets/products/Hospital 3 seaters chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(36, 7, 'Corportate 3 seater chair', 14999.00, 20000.00, 'Premium three-seater chair designed for corporate environments with high-quality materials.', 'Seating Capacity: 3 persons. Frame Material: High-quality stainless steel or chrome-plated metal for strength and corrosion resistance. Seat & Backrest: Ergonomic design with perforated metal mesh and padded leather or synthetic cushioning for comfort. Armrests: Smoothly curved metal armrests on both ends for support and aesthetics. Legs/Base: Strong, arched metal legs with anti-slip rubber foot caps for stability. Finish: Polished silver finish with black seating for a professional look. Usage: Ideal for airports, reception areas, clinics, and public waiting zones. Maintenance: Easy to clean and resistant to wear and tear', 'frontend/assets/products/Corportate 3 seater chair.jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(37, 7, 'Public 3 seater chair (17 kg )', 4499.00, 8600.00, 'This is a three-seater metal waiting chair, designed for use in offices, hospitals, and public spaces.', '3-Seater Design: Accommodates three people comfortably. Durable Metal Frame: Made from high-quality steel for long-lasting strength and stability. Powder-Coated Finish: Rust-resistant and easy to clean, maintaining a polished look. Ergonomic Backrest & Seat: Provides proper posture support for extended sitting. Fixed Armrests: Smooth curved arms for added comfort and support. Sturdy Leg Base: Equipped with anti-slip foot caps for stability and floor protection. Low Maintenance: Easy to clean and suitable for heavy public use. Color: Typically available in black or metallic finish for a professional appearance.', 'frontend/assets/products/Public 3 seater chair (17 kg ).jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55'),
(38, 7, 'Public 3 seaters chair (14 kg )', 4499.00, 8000.00, 'This is a three-seater metal waiting chair, designed for use in offices, hospitals, and public spaces.', '3-Seater Design: Accommodates three people comfortably. Durable Metal Frame: Made from high-quality steel for long-lasting strength and stability. Powder-Coated Finish: Rust-resistant and easy to clean, maintaining a polished look. Ergonomic Backrest & Seat: Provides proper posture support for extended sitting. Fixed Armrests: Smooth curved arms for added comfort and support. Sturdy Leg Base: Equipped with anti-slip foot caps for stability and floor protection. Low Maintenance: Easy to clean and suitable for heavy public use. Color: Typically available in black or metallic finish for a professional appearance.', 'frontend/assets/products/Public 3 seaters chair (14 kg ).jfif', 1, '2025-10-29 12:23:55', '2025-10-29 12:23:55');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`productId`),
  ADD KEY `products_catid_foreign` (`catId`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `productId` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=39;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `products`
--
ALTER TABLE `products`
  ADD CONSTRAINT `products_catid_foreign` FOREIGN KEY (`catId`) REFERENCES `categories` (`catId`) ON DELETE SET NULL;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
